### ISSUE TITLE
Fixing (Type of entity).FirstOrDefaultAsync() for GUID

### ISSUE THREAD

**Issue by bjornarjatten** [simoboye/BDSA2020#13]
(Type of entity).FirstOrDefaultAsync() is now giving a random first (as there is created a new GUID for each of the test entries each time). This is currently solved by giving a permanent GUID to one of the test entries, however this is not a permanent solution.

**Comment by bjornarjatten** [comment]
This is a problem for both student and company, possible placement descriptions aswell

**Comment by bjornarjatten** [comment]
As well as PlacementDescriptions 💯

**Comment by simoboye** [comment]
I think that we should maybe avoid giving the context more responsibilities than it already has. Since we would never set the populate the database when building the code, we should probably use some special test data when we run unit tests.

Therefore I'm not sure that we can avoid using the hardcoded GUI's.
